Repository meta-pytorch/torchcodec, pull requests merged in 2024-10, with the labels that each got.

#221 Add Random index-based clip sampler - part 1
  src/torchcodec/__init__.py
  src/torchcodec/samplers/__init__.py
  src/torchcodec/samplers/_implem.py
  test/conftest.py
  test/samplers/test_samplers.py
Labels: CLA Signed

#233 Rename SimpleVideoDecoder to VideoDecoder
  .github/ISSUE_TEMPLATE/bug-report.yml
  README.md
  benchmarks/decoders/benchmark_decoders.py
  docs/source/api_ref_decoders.rst
  examples/basic_example.py
  src/torchcodec/decoders/__init__.py
  src/torchcodec/decoders/_core/_metadata.py
  src/torchcodec/decoders/_video_decoder.py
  src/torchcodec/samplers/_implem.py
  test/decoders/test_video_decoder.py
  test/samplers/test_samplers.py
Labels: CLA Signed

#236 Update version to 0.0.4.dev in main branch
  src/torchcodec/__init__.py
Labels: CLA Signed

#240 Add regular index-based sampler - part 1
  src/torchcodec/samplers/__init__.py
  src/torchcodec/samplers/_implem.py
  test/samplers/test_samplers.py
Labels: CLA Signed

#234 Added skeleton code for cuda builds
  .github/workflows/cuda_tests.yaml
  setup.py
  src/torchcodec/decoders/_core/CMakeLists.txt
  src/torchcodec/decoders/_core/CPUOnlyDevice.cpp
  src/torchcodec/decoders/_core/CudaDevice.cpp
  src/torchcodec/decoders/_core/DeviceInterface.h
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
  src/torchcodec/decoders/_core/VideoDecoderOps.cpp
  src/torchcodec/decoders/_core/VideoDecoderOps.h
  src/torchcodec/decoders/_core/video_decoder_ops.py
  test/decoders/test_video_decoder_ops.py
  test/utils.py
Labels: CLA Signed

#243 Fix broken C++ code
  benchmarks/decoders/BenchmarkDecodersMain.cpp
Labels: CLA Signed

#244 Make it clear that the device interface is only for non-CPU devices. This makes the code simpler to reason about
  src/torchcodec/decoders/_core/CPUOnlyDevice.cpp
  src/torchcodec/decoders/_core/CudaDevice.cpp
  src/torchcodec/decoders/_core/DeviceInterface.h
  src/torchcodec/decoders/_core/VideoDecoder.cpp
Labels: CLA Signed

#241 Samplers: add support for edge-case policies
  src/torchcodec/samplers/_implem.py
  test/samplers/test_samplers.py
Labels: CLA Signed

#245 Speed-up samplers by avoiding backwards seeks
  src/torchcodec/samplers/_implem.py
Labels: CLA Signed

#247 Refactor Frame and FrameBatch into their own source file
  docs/source/api_ref_decoders.rst
  docs/source/api_ref_torchcodec.rst
  docs/source/index.rst
  examples/basic_example.py
  src/torchcodec/__init__.py
  src/torchcodec/_frame.py
  src/torchcodec/decoders/__init__.py
  src/torchcodec/decoders/_video_decoder.py
  src/torchcodec/samplers/_implem.py
  test/samplers/test_samplers.py
Labels: CLA Signed

#248 New samplers benchmark
  benchmarks/samplers/benchmark_samplers.py
Labels: CLA Signed

#237 Use `int` instead of `numbers.integral` in docstring
  src/torchcodec/decoders/_video_decoder.py
Labels: CLA Signed

#242 Add CUDA decoding support
  benchmarks/decoders/gpu_benchmark.py
  src/torchcodec/decoders/_core/CMakeLists.txt
  src/torchcodec/decoders/_core/CPUOnlyDevice.cpp
  src/torchcodec/decoders/_core/CudaDevice.cpp
  src/torchcodec/decoders/_core/DeviceInterface.h
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
  src/torchcodec/decoders/_core/VideoDecoderOps.cpp
  test/decoders/test_video_decoder_ops.py
Labels: CLA Signed

#250 Add time-based regular sampler
  src/torchcodec/samplers/__init__.py
  src/torchcodec/samplers/_implem.py
  test/samplers/test_samplers.py
Labels: CLA Signed

#257 Indexes -> Indices
  benchmarks/decoders/benchmark_decoders.py
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
  src/torchcodec/decoders/_core/VideoDecoderOps.cpp
  test/decoders/VideoDecoderTest.cpp
Labels: CLA Signed

#249 Use pathlib instead of os.path
  benchmarks/decoders/benchmark_decoders.py
  benchmarks/decoders/gpu_benchmark.py
  src/torchcodec/_internally_replaced_utils.py
  test/decoders/manual_smoke_test.py
Labels: CLA Signed

#255 Add Random time-based sampler
  benchmarks/samplers/benchmark_samplers.py
  src/torchcodec/samplers/__init__.py
  src/torchcodec/samplers/_implem.py
  test/samplers/test_samplers.py
Labels: CLA Signed

#259 Split samplers implementation across different files
  src/torchcodec/samplers/__init__.py
  src/torchcodec/samplers/_common.py
  src/torchcodec/samplers/_implem.py
  src/torchcodec/samplers/_index_based.py
  src/torchcodec/samplers/_time_based.py
  test/samplers/test_policy.py
  test/samplers/test_samplers.py
Labels: CLA Signed

#258 Improve cuda decoding performance by ~2x using decoder caching
  .github/workflows/cuda_tests.yaml
  src/torchcodec/decoders/_core/CPUOnlyDevice.cpp
  src/torchcodec/decoders/_core/CudaDevice.cpp
  src/torchcodec/decoders/_core/DeviceInterface.h
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
  test/utils.py
Labels: CLA Signed

#261 Fix typo in logger
  src/torchcodec/decoders/_core/VideoDecoder.cpp
Labels: CLA Signed

#264 Unbreak CI by using C++17 code
  src/torchcodec/decoders/_core/VideoDecoderOps.cpp
Labels: CLA Signed

#271 Remove unnecessary optionality
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
Labels: CLA Signed

#273 Fix cuda builds for lower than 6.1 ffmpeg versions
  .github/workflows/cuda_tests.yaml
  src/torchcodec/decoders/_core/CudaDevice.cpp
Labels: CLA Signed

#275 Lint fix.
  src/torchcodec/decoders/_core/VideoDecoder.cpp
Labels: CLA Signed

#277 Rework HWC / CHW dimension order conversions
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  test/decoders/test_video_decoder_ops.py
Labels: CLA Signed

#278 Let getFramesAtIndices rely on getFrameAtIndex
  src/torchcodec/decoders/_core/VideoDecoder.cpp
Labels: CLA Signed

#279 Reorder inits to match declaration
  src/torchcodec/decoders/_core/VideoDecoder.cpp
Labels: CLA Signed

#280 Add sort and dedup logic in C++ to `getFramesAtIndices`
  benchmarks/decoders/benchmark_decoders.py
  src/torchcodec/_samplers/video_clip_sampler.py
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoderOps.cpp
  src/torchcodec/decoders/_core/VideoDecoderOps.h
  src/torchcodec/decoders/_core/video_decoder_ops.py
  test/decoders/test_video_decoder_ops.py
Labels: CLA Signed

#282 Add sort and dedup logic in C++ with new `getFramesDisplayedByTimestamps` method / core API
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
  src/torchcodec/decoders/_core/VideoDecoderOps.cpp
  src/torchcodec/decoders/_core/VideoDecoderOps.h
  src/torchcodec/decoders/_core/__init__.py
  src/torchcodec/decoders/_core/video_decoder_ops.py
  test/decoders/test_video_decoder_ops.py
Labels: CLA Signed

#272 Add ability to build cuda wheels
  .github/workflows/linux_cuda_wheel.yaml
  packaging/post_build_script.sh
  src/torchcodec/decoders/_core/CMakeLists.txt
  test/utils.py
Labels: CLA Signed, ciflow/binaries/all

#283 Frame and FrameBatch improvements
  src/torchcodec/_frame.py
  test/test_frame_dataclasses.py
Labels: CLA Signed

#287 Fix pts -> index conversion in `get_frame_at_timestamps[_in_range]`
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
  test/decoders/test_video_decoder_ops.py
Labels: bug, CLA Signed

#284 Speed-up time-based samplers by 20X and index-based by 1.5X
  src/torchcodec/samplers/_common.py
  src/torchcodec/samplers/_index_based.py
  src/torchcodec/samplers/_time_based.py
  test/samplers/test_samplers.py
Labels: CLA Signed

#289 Prevent CUDA tests from running if there is a build problem
  .github/workflows/linux_cuda_wheel.yaml
Labels: CLA Signed

#297 Test samplers against reference
  src/torchcodec/samplers/_time_based.py
  test/samplers/test_samplers.py
Labels: CLA Signed

#294 Add fps info to samplers benchmark
  benchmarks/samplers/benchmark_samplers.py
Labels: CLA Signed

#292 Use test-infra's main branch now that https://github.com/pytorch/test-infra/pull/5789 is merged
  .github/workflows/linux_cuda_wheel.yaml
Labels: CLA Signed

#298 Install cuda-enabled torchvision
  .github/workflows/linux_cuda_wheel.yaml
Labels: CLA Signed

#300 Use main branch of test-infra
  .github/workflows/linux_cuda_wheel.yaml
Labels: CLA Signed

#302 Rename `get_frames_at` and `get_frames_displayed_at`
  README.md
  examples/basic_example.py
  src/torchcodec/decoders/_video_decoder.py
  test/decoders/test_video_decoder.py
Labels: CLA Signed

#230 Build Mac wheels in CI
  .github/workflows/linux_wheel.yaml
  .github/workflows/macos_wheel.yaml
  packaging/check_glibcxx.py
  packaging/post_build_script.sh
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoderOps.cpp
Labels: CLA Signed

#299 Delete cuda_tests.yaml -- we have cuda tests in linux_cuda_wheel.yaml
  .github/workflows/cuda_tests.yaml
Labels: CLA Signed

#290 No-op change: move benchmarking code to a library
  benchmarks/decoders/benchmark_decoders.py
  benchmarks/decoders/benchmark_decoders_library.py
Labels: CLA Signed

#291 Add option for the user to pass in ffmpeg thread count
  src/torchcodec/decoders/_video_decoder.py
  test/decoders/test_video_decoder.py
Labels: CLA Signed

#311 Fix indentation
  benchmarks/decoders/benchmark_decoders_library.py
Labels: CLA Signed

#295 Honor `preAllocatedOutputTensor` with filtergraph
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  test/decoders/VideoDecoderTest.cpp
Labels: CLA Signed

#308 Relax test constraint for ffmpeg versions as they can be arbitrary
  .github/workflows/linux_cuda_wheel.yaml
  test/decoders/test_video_decoder_ops.py
Labels: CLA Signed

#313 Make ffmpeg build workflow execute when script changes
  .github/workflows/build_ffmpeg.yaml
Labels: CLA Signed

#314 Added the ability to benchmark on a directory and output to a chart
  benchmarks/decoders/benchmark_decoders.py
  benchmarks/decoders/benchmark_decoders_library.py
Labels: CLA Signed

#309 Add workflow for reference resource generation
  .github/workflows/reference_resources.yaml
Labels: CLA Signed

#296 Indexing 4D FrameBatch now returns FrameBatch
  src/torchcodec/_frame.py
  test/test_frame_dataclasses.py
Labels: CLA Signed

#310 Remove `get_frame_by_name` test util
  test/decoders/test_video_decoder.py
  test/decoders/test_video_decoder_ops.py
  test/resources/nasa_13013.mp4.stream3.frame000180.pt
  test/resources/nasa_13013.mp4.stream3.frame000289.pt
  test/utils.py
Labels: CLA Signed

#315 Added benchmark chart to README.md
  README.md
  benchmarks/decoders/benchmark_decoders_library.py
  benchmarks/decoders/benchmark_readme_chart.png
  benchmarks/decoders/generate_readme_chart.py
Labels: CLA Signed

#317 Refac: Straightforward output shape permutation
  benchmarks/decoders/BenchmarkDecodersMain.cpp
  packaging/check_glibcxx.py
  src/torchcodec/decoders/_core/CudaDevice.cpp
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
  src/torchcodec/decoders/_core/VideoDecoderOps.cpp
  test/decoders/VideoDecoderTest.cpp
Labels: CLA Signed

#323 Add a call to ffmpeg in CUDA wheels as an assertion
  .github/workflows/linux_cuda_wheel.yaml
Labels: CLA Signed

#319 Add batch decoding support to CUDA
  benchmarks/samplers/benchmark_samplers.py
  src/torchcodec/decoders/_core/CPUOnlyDevice.cpp
  src/torchcodec/decoders/_core/CudaDevice.cpp
  src/torchcodec/decoders/_core/DeviceInterface.h
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_video_decoder.py
  test/decoders/test_video_decoder_ops.py
  test/utils.py
Labels: CLA Signed

#322 Remove preAllocatedTensor from getFrameAtIndex
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
  test/decoders/VideoDecoderTest.cpp
Labels: CLA Signed

#327 Generalize README benchmark
  benchmarks/decoders/benchmark_decoders_library.py
  benchmarks/decoders/generate_readme_chart.py
Labels: CLA Signed

#328 Seperate out readme experiments from chart generation
  README.md
  benchmarks/decoders/benchmark_decoders_library.py
  benchmarks/decoders/benchmark_readme_chart.png
  benchmarks/decoders/benchmark_readme_data.json
  benchmarks/decoders/generate_readme_chart.py
  benchmarks/decoders/generate_readme_data.py
Labels: CLA Signed
