Repository meta-pytorch/torchcodec, pull requests merged in 2024-08, with the labels that each got.

#161 Update current dev version to `0.0.2.dev`
  src/torchcodec/__init__.py
Labels: CLA Signed

#160 Build wheels on test-infra machines
  .github/workflows/wheel.yaml
  packaging/env_var_script.sh
  packaging/fake_smoke_test.py
  packaging/post_build_script.sh
Labels: CLA Signed

#162 Move utilities from .github/scripts/ into packaging/
  .github/scripts/assert_ffmpeg_not_installed.sh
  .github/workflows/build_ffmpeg.yaml
  .github/workflows/wheel.yaml
  packaging/build_ffmpeg.sh
  packaging/check_glibcxx.py
  packaging/helpers.sh
  packaging/post_build_script.sh
Labels: CLA Signed

#169 Prepare 0.0.2
  benchmarks/decoders/BenchmarkDecodersMain.cpp
  benchmarks/decoders/gpu_benchmark.py
  examples/basic_example.py
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
  src/torchcodec/decoders/_core/VideoDecoderOps.cpp
  src/torchcodec/decoders/_simple_video_decoder.py
  test/decoders/VideoDecoderTest.cpp
  test/decoders/test_simple_video_decoder.py
Labels: CLA Signed

#171 0.0.2 release
  .github/workflows/wheel.yaml
  src/torchcodec/__init__.py
Labels: CLA Signed, ciflow/binaries/all

#168 Reword the README's intro
  README.md
  docs/source/index.rst
Labels: CLA Signed

#175 Typo fix: FMPEG -> FFmpeg
  README.md
Labels: CLA Signed

#170 Fix wrong link to PTS term in docs
  src/torchcodec/decoders/_simple_video_decoder.py
Labels: CLA Signed

#178 [torchcodec] Return subsequent frame if FFMPEG seeks past end of the frame
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  test/decoders/test_simple_video_decoder.py
  test/generate_reference_resources.sh
  test/resources/h265_video.mp4
  test/resources/h265_video.mp4.frame000006.pt
  test/utils.py
Labels: CLA Signed, fb-exported

#177 Update build command
  .github/workflows/wheel.yaml
  packaging/env_var_script.sh
Labels: CLA Signed

#184 0.0.3 release
  .github/workflows/wheel.yaml
  examples/basic_example.py
  src/torchcodec/__init__.py
Labels: CLA Signed, ciflow/binaries/all

#185 Fix FFmpeg URL in rst docs
  docs/source/index.rst
Labels: CLA Signed

#187 Add CI for linux cuda
  .github/workflows/test_linux_cuda.yaml
  src/torchcodec/decoders/_core/CMakeLists.txt
Labels: CLA Signed

#195 Lower size of temporary buffer used by ffmpeg
  src/torchcodec/decoders/_core/VideoDecoder.cpp
Labels: CLA Signed

#196 Temporary revert GPU support
  .github/workflows/test_linux_cuda.yaml
  CMakeLists.txt
  README.md
  benchmarks/decoders/BenchmarkDecodersMain.cpp
  benchmarks/decoders/gpu_benchmark.py
  examples/basic_example.py
  setup.py
  src/torchcodec/_samplers/video_clip_sampler.py
  src/torchcodec/decoders/_core/CMakeLists.txt
  src/torchcodec/decoders/_core/FFMPEGCommon.h
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
  src/torchcodec/decoders/_core/VideoDecoderOps.cpp
  src/torchcodec/decoders/_core/VideoDecoderOps.h
  src/torchcodec/decoders/_core/video_decoder_ops.py
  src/torchcodec/decoders/_simple_video_decoder.py
  test/decoders/CMakeLists.txt
  test/decoders/VideoDecoderTest.cpp
  test/decoders/manual_smoke_test.py
  test/decoders/test_simple_video_decoder.py
  test/generate_reference_resources.sh
  test/resources/nasa_13013.mp4.frame000001.cuda.pt
  test/resources/nasa_13013.mp4.frame000002.cuda.pt
  test/samplers/test_video_clip_sampler.py
Labels: CLA Signed

#194 Add flags to set benchmark video file paths
  benchmarks/decoders/benchmark_decoders.py
Labels: CLA Signed

#198 [Unrevert] Add a NoDemux suffix to functions that do not demux (#147)
  benchmarks/decoders/BenchmarkDecodersMain.cpp
  src/torchcodec/decoders/_core/VideoDecoder.cpp
  src/torchcodec/decoders/_core/VideoDecoder.h
  src/torchcodec/decoders/_core/VideoDecoderOps.cpp
  test/decoders/VideoDecoderTest.cpp
Labels: CLA Signed
