Repository meta-pytorch/torchcodec, pull requests merged in 2025-07, with the labels that each got.

#755 Explicitly close encoded file
  src/torchcodec/_core/Encoder.cpp
Labels: CLA Signed

#752 Windows: Add FFmpeg build job
  .github/workflows/build_ffmpeg.yaml
  packaging/build_ffmpeg.bat
  packaging/vc_env_helper.bat
Labels: CLA Signed

#763 Use nullptr instead of NULL
  src/torchcodec/_core/Encoder.cpp
Labels: CLA Signed

#768 Refactor C++ library names
  src/torchcodec/_core/CMakeLists.txt
  src/torchcodec/_core/ops.py
  src/torchcodec/_internally_replaced_utils.py
Labels: CLA Signed

#783 Fix typing error
  src/torchcodec/_core/ops.py
  src/torchcodec/_internally_replaced_utils.py
Labels: CLA Signed

#764 Add stream_index seek mode, read frame index and update metadata
  src/torchcodec/_core/SingleStreamDecoder.cpp
  src/torchcodec/_core/SingleStreamDecoder.h
  src/torchcodec/_core/custom_ops.cpp
  src/torchcodec/_core/ops.py
  test/test_metadata.py
  test/test_ops.py
  test/utils.py
Labels: CLA Signed

#773 Close avio object *before* encode destruction. And flush, too.
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
Labels: CLA Signed

#786 Release 0.5
  .github/workflows/docs.yaml
  .github/workflows/linux_cuda_wheel.yaml
  .github/workflows/linux_wheel.yaml
  .github/workflows/macos_wheel.yaml
  version.txt
Labels: CLA Signed, ciflow/binaries/all

#785 Avoid copies of frame mappings
  src/torchcodec/_core/custom_ops.cpp
Labels: CLA Signed

#777 Avoid silently wrong results on 10bit CUDA
  src/torchcodec/_core/CudaDeviceInterface.cpp
  test/resources/h264_10bits.mp4
  test/resources/h265_10bits.mp4
  test/test_decoders.py
  test/utils.py
Labels: bug, CLA Signed

#784 Consistently use ptsToSeconds
  src/torchcodec/_core/SingleStreamDecoder.cpp
  test/VideoDecoderTest.cpp
  test/test_ops.py
Labels: CLA Signed

#792 Support CPU fallback for videos that don't get decoded by nvdec
  src/torchcodec/_core/CudaDeviceInterface.cpp
  test/test_decoders.py
Labels: CLA Signed
