Repository meta-pytorch/torchcodec, pull requests merged in 2025-05, with the labels that each got.

#667 Encoding: address some TODOs
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
  src/torchcodec/_core/custom_ops.cpp
  test/test_ops.py
Labels: CLA Signed

#636 Define CpuDeviceInterface
  src/torchcodec/_core/CMakeLists.txt
  src/torchcodec/_core/CpuDeviceInterface.cpp
  src/torchcodec/_core/CpuDeviceInterface.h
  src/torchcodec/_core/CudaDeviceInterface.cpp
  src/torchcodec/_core/CudaDeviceInterface.h
  src/torchcodec/_core/DeviceInterface.cpp
  src/torchcodec/_core/DeviceInterface.h
  src/torchcodec/_core/Frame.cpp
  src/torchcodec/_core/Frame.h
  src/torchcodec/_core/SingleStreamDecoder.cpp
  src/torchcodec/_core/SingleStreamDecoder.h
Labels: CLA Signed

#678 AudioDecoder: specify desired num_channels
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/FFMPEGCommon.cpp
  src/torchcodec/_core/FFMPEGCommon.h
  src/torchcodec/_core/SingleStreamDecoder.cpp
  src/torchcodec/_core/StreamOptions.h
  src/torchcodec/_core/custom_ops.cpp
  src/torchcodec/_core/ops.py
  src/torchcodec/decoders/_audio_decoder.py
  test/test_decoders.py
Labels: CLA Signed

#682 Fix pts <-> seconds conversions
  src/torchcodec/_core/SingleStreamDecoder.cpp
Labels: bug, CLA Signed

#683 Fallback to DTS if PTS info doesn't exist
  src/torchcodec/_core/SingleStreamDecoder.cpp
  src/torchcodec/_core/_metadata.py
  test/test_decoders.py
Labels: CLA Signed

#685 Remove 'unstable API' notice from README
  README.md
  docs/source/index.rst
Labels: CLA Signed

#680 Renaming of C++ variables: `source*` -> `src*`
  src/torchcodec/_core/FFMPEGCommon.cpp
  src/torchcodec/_core/FFMPEGCommon.h
  src/torchcodec/_core/SingleStreamDecoder.cpp
Labels: CLA Signed

#688 Avoid shadowing local variables
  src/torchcodec/_core/SingleStreamDecoder.cpp
Labels: CLA Signed

#686 Release 0.4.0
  .github/workflows/build_ffmpeg.yaml
  .github/workflows/docs.yaml
  .github/workflows/linux_cuda_wheel.yaml
  .github/workflows/linux_wheel.yaml
  .github/workflows/macos_wheel.yaml
  setup.py
  version.txt
Labels: CLA Signed, ciflow/binaries/all

#687 Remove +cpu from version name
  setup.py
Labels: CLA Signed

#692 Add `AudioEncoder` public Python API
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/ops.py
  src/torchcodec/encoders/__init__.py
  src/torchcodec/encoders/_audio_encoder.py
  test/test_encoders.py
  test/test_ops.py
Labels: CLA Signed

#693 Audio encoding: support custom `num_channels`
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
  src/torchcodec/_core/FFMPEGCommon.cpp
  src/torchcodec/_core/FFMPEGCommon.h
  src/torchcodec/_core/custom_ops.cpp
  src/torchcodec/_core/ops.py
  src/torchcodec/encoders/_audio_encoder.py
  test/test_ops.py
Labels: CLA Signed

#698 Use `AudioStreamOptions` in `AudioEncoder`
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
  src/torchcodec/_core/StreamOptions.h
  src/torchcodec/_core/custom_ops.cpp
Labels: CLA Signed

#704 Refactor audio sample conversion in encoder
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
Labels: CLA Signed
