Repository meta-pytorch/torchcodec, pull requests merged in 2025-09, with the labels that each got.

#868 Fix `NVDEC -> NPP` CUDA stream sync issue
  src/torchcodec/_core/CudaDeviceInterface.cpp
Labels: bug, CLA Signed

#865 Fix audio decoding bug with FFmpeg4 by setting channel_layout
  src/torchcodec/_core/FFMPEGCommon.cpp
  test/resources/sine_mono_s16.wav.stream0.all_frames.pt
  test/test_decoders.py
Labels: bug, CLA Signed

#870 Remove discard check when scanning file
  src/torchcodec/_core/SingleStreamDecoder.cpp
Labels: CLA Signed

#872 Release 0.7
  .github/workflows/build_ffmpeg.yaml
  .github/workflows/docs.yaml
  .github/workflows/linux_cuda_wheel.yaml
  .github/workflows/linux_wheel.yaml
  .github/workflows/macos_wheel.yaml
  .github/workflows/windows_wheel.yaml
  version.txt
Labels: CLA Signed, ciflow/binaries/all

#869 Refactor context structs to use constructors
  src/torchcodec/_core/CpuDeviceInterface.cpp
  src/torchcodec/_core/CpuDeviceInterface.h
  src/torchcodec/_core/FilterGraph.cpp
  src/torchcodec/_core/FilterGraph.h
Labels: CLA Signed

#874 Remove outdated comment
  src/torchcodec/_core/DeviceInterface.h
Labels: CLA Signed

#875 Assert `deviceInterface_` exists when it should
  src/torchcodec/_core/SingleStreamDecoder.cpp
Labels: CLA Signed

#881 [Release 0.7] Use custom test-infra branch for windows build
  .github/workflows/windows_wheel.yaml
  version.txt
Labels: CLA Signed, ciflow/binaries/all

#871 [Release 0.7] remove custom_frame_mappings from 0.7 release branch
  src/torchcodec/decoders/_video_decoder.py
  test/test_decoders.py
Labels: CLA Signed, ciflow/binaries/all

#880 Let `get_frames_at` and `get_frames_played_at` accept tensor indices
  src/torchcodec/decoders/_video_decoder.py
  test/test_decoders.py
Labels: CLA Signed

#882 [Release 0.7 Cherry-Pick] Let `get_frames_at` and `get_frames_played_at` accept tensor indices …
  src/torchcodec/decoders/_video_decoder.py
  test/test_decoders.py
Labels: CLA Signed

#900 Disable ffprobe test internally
  test/test_decoders.py
  test/test_ops.py
Labels: CLA Signed, fb-exported, meta-exported

#898 Handle AVCodec fields deprecated in FFmpeg 7
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/FFMPEGCommon.cpp
  src/torchcodec/_core/FFMPEGCommon.h
Labels: CLA Signed

#904 Remove TORCH_CHECKS on avcodec_get_supported_config output
  src/torchcodec/_core/FFMPEGCommon.cpp
Labels: CLA Signed

#892 Add `--output-results` option to benchmark utility
  benchmarks/decoders/benchmark_decoders.py
Labels: CLA Signed, fb-exported, meta-exported

#887 Add custom_frame_mappings tutorial and optimizations
  docs/source/conf.py
  examples/decoding/custom_frame_mappings.py
  src/torchcodec/_core/SingleStreamDecoder.cpp
  src/torchcodec/decoders/_video_decoder.py
  test/test_ops.py
Labels: CLA Signed
