Repository meta-pytorch/torchcodec, pull requests merged in 2025-04, with the labels that each got.

#604 Fix a typo in contribution doc
  CONTRIBUTING.md
Labels: CLA Signed

#597 Add `soundfile` backend to audio decoding benchmarks
  benchmarks/decoders/benchmark_audio_decoders.py
Labels: CLA Signed

#603 Refactor C++ ops implementations
  src/torchcodec/decoders/_core/CMakeLists.txt
  src/torchcodec/decoders/_core/VideoDecoderOps.h
  src/torchcodec/decoders/_core/custom_ops.cpp
  src/torchcodec/decoders/_core/pybind_ops.cpp
Labels: CLA Signed

#609 Move `torchcodec/decoders/_core` into `torchcodec/_core`
  CMakeLists.txt
  benchmarks/decoders/benchmark_decoders_library.py
  benchmarks/decoders/gpu_benchmark.py
  benchmarks/decoders/memprofile_decoders.py
  src/torchcodec/_core/AVIOBytesContext.cpp
  src/torchcodec/_core/AVIOBytesContext.h
  src/torchcodec/_core/AVIOContextHolder.cpp
  src/torchcodec/_core/AVIOContextHolder.h
  src/torchcodec/_core/AVIOFileLikeContext.cpp
  src/torchcodec/_core/AVIOFileLikeContext.h
  src/torchcodec/_core/CMakeLists.txt
  src/torchcodec/_core/CPUOnlyDevice.cpp
  src/torchcodec/_core/CudaDevice.cpp
  src/torchcodec/_core/DeviceInterface.h
  src/torchcodec/_core/FFMPEGCommon.cpp
  src/torchcodec/_core/FFMPEGCommon.h
  src/torchcodec/_core/VideoDecoder.cpp
  src/torchcodec/_core/VideoDecoder.h
  src/torchcodec/_core/__init__.py
  src/torchcodec/_core/_metadata.py
  src/torchcodec/_core/custom_ops.cpp
  src/torchcodec/_core/fetch_and_expose_non_gpl_ffmpeg_libs.cmake
  src/torchcodec/_core/ops.py
  src/torchcodec/_core/pybind_ops.cpp
  src/torchcodec/_samplers/video_clip_sampler.py
  src/torchcodec/decoders/__init__.py
  src/torchcodec/decoders/_audio_decoder.py
  src/torchcodec/decoders/_decoder_utils.py
  src/torchcodec/decoders/_video_decoder.py
  test/decoders/VideoDecoderTest.cpp
  test/decoders/manual_smoke_test.py
  test/decoders/test_decoders.py
  test/decoders/test_metadata.py
  test/decoders/test_ops.py
  test/utils.py
Labels: CLA Signed

#607 Fix VideoDecoder device argument to accept torch.device
  src/torchcodec/decoders/_video_decoder.py
  test/decoders/test_decoders.py
Labels: CLA Signed

#612 Remove `manual_smoke_test.py`
  .github/workflows/linux_cuda_wheel.yaml
  .github/workflows/linux_wheel.yaml
  .github/workflows/macos_wheel.yaml
  test/decoders/manual_smoke_test.py
Labels: CLA Signed

#611 VideoDecoder -> SingleStreamDecoder
  src/torchcodec/_core/AVIOContextHolder.h
  src/torchcodec/_core/CMakeLists.txt
  src/torchcodec/_core/CPUOnlyDevice.cpp
  src/torchcodec/_core/CudaDevice.cpp
  src/torchcodec/_core/DeviceInterface.h
  src/torchcodec/_core/SingleStreamDecoder.cpp
  src/torchcodec/_core/SingleStreamDecoder.h
  src/torchcodec/_core/custom_ops.cpp
  src/torchcodec/_core/pybind_ops.cpp
  test/decoders/VideoDecoderTest.cpp
Labels: CLA Signed

#610 Add ops test for file-like seeks
  test/decoders/test_ops.py
Labels: CLA Signed

#613 Flatten test folder
  CMakeLists.txt
  test/CMakeLists.txt
  test/VideoDecoderTest.cpp
  test/decoders/__init__.py
  test/samplers/__init__.py
  test/test_decoders.py
  test/test_metadata.py
  test/test_ops.py
  test/test_policy.py
  test/test_samplers.py
  test/test_video_clip_sampler.py
Labels: CLA Signed

#615 Remove redundant includes
  src/torchcodec/_core/SingleStreamDecoder.cpp
Labels: CLA Signed

#614 Add file like bad scenario testing
  test/test_ops.py
Labels: CLA Signed

#524 Audio encoding - part 1 of N
  src/torchcodec/_core/CMakeLists.txt
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
  src/torchcodec/_core/FFMPEGCommon.cpp
  src/torchcodec/_core/FFMPEGCommon.h
  src/torchcodec/_core/SingleStreamDecoder.cpp
  src/torchcodec/_core/SingleStreamDecoder.h
  src/torchcodec/_core/__init__.py
  src/torchcodec/_core/custom_ops.cpp
  src/torchcodec/_core/ops.py
  test/test_ops.py
  test/utils.py
Labels: CLA Signed

#616 Enable public decoder creation with file like object
  src/torchcodec/_core/ops.py
  src/torchcodec/decoders/_audio_decoder.py
  src/torchcodec/decoders/_decoder_utils.py
  src/torchcodec/decoders/_video_decoder.py
  test/test_decoders.py
Labels: CLA Signed

#620 Move stream options and frame output structs to dedicated headers
  src/torchcodec/_core/CudaDevice.cpp
  src/torchcodec/_core/CudaDevice.h
  src/torchcodec/_core/DeviceInterface.h
  src/torchcodec/_core/Frame.h
  src/torchcodec/_core/Metadata.h
  src/torchcodec/_core/SingleStreamDecoder.cpp
  src/torchcodec/_core/SingleStreamDecoder.h
  src/torchcodec/_core/StreamOptions.h
  src/torchcodec/_core/custom_ops.cpp
  test/VideoDecoderTest.cpp
Labels: CLA Signed

#623 Add bit_rate parameter to encoder
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
  src/torchcodec/_core/custom_ops.cpp
  src/torchcodec/_core/ops.py
  test/test_ops.py
Labels: CLA Signed

#626 Rename CudaDevice to CudaDeviceInterface
  src/torchcodec/_core/CMakeLists.txt
  src/torchcodec/_core/CudaDeviceInterface.cpp
  src/torchcodec/_core/CudaDeviceInterface.h
Labels: CLA Signed

#624 Encoder: properly validate sample rate parameter
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
  test/test_ops.py
Labels: CLA Signed

#625 Disable FFmpeg logs for encoder
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/FFMPEGCommon.cpp
  src/torchcodec/_core/FFMPEGCommon.h
  src/torchcodec/_core/SingleStreamDecoder.cpp
  src/torchcodec/_core/SingleStreamDecoder.h
Labels: CLA Signed

#627 Skip ffmpeg CLI test internally
  test/test_ops.py
Labels: CLA Signed

#631 [torchcodec] delay device map init to runtime and fix targets
  src/torchcodec/_core/DeviceInterface.cpp
Labels: CLA Signed, fb-exported

#633 `bit_rate` -> `bitRate` for C++ code
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
Labels: CLA Signed

#629 Move sample rate and sample format conversion utils into `FFMPEGCommon.cpp`
  src/torchcodec/_core/FFMPEGCommon.cpp
  src/torchcodec/_core/FFMPEGCommon.h
  src/torchcodec/_core/SingleStreamDecoder.cpp
  src/torchcodec/_core/SingleStreamDecoder.h
Labels: CLA Signed

#630 Encoding: support wav, flac etc.
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
  test/test_ops.py
Labels: CLA Signed

#644 Add test for file-like read() method sending fewer bytes than requested
  test/test_ops.py
Labels: CLA Signed

#645 Remove our own manywheel fixup
  packaging/post_build_script.sh
Labels: CLA Signed

#638 File like tutorial
  docs/requirements.txt
  examples/file_like.py
  src/torchcodec/decoders/_audio_decoder.py
  src/torchcodec/decoders/_video_decoder.py
Labels: CLA Signed

#648 Remove torchvision test dependency
  .github/workflows/linux_wheel.yaml
  .github/workflows/macos_wheel.yaml
  .github/workflows/reference_resources.yaml
  CONTRIBUTING.md
Labels: CLA Signed

#646 Put back version symbol wheel checks
  packaging/check_glibcxx.py
  packaging/post_build_script.sh
Labels: CLA Signed

#650 Final doc touches before release
  README.md
  docs/source/conf.py
  docs/source/index.rst
  examples/basic_example.py
  src/torchcodec/decoders/_video_decoder.py
Labels: CLA Signed

#651 Release 0.3.0
  .github/workflows/build_ffmpeg.yaml
  .github/workflows/docs.yaml
  .github/workflows/linux_cuda_wheel.yaml
  .github/workflows/linux_wheel.yaml
  .github/workflows/macos_wheel.yaml
  setup.py
  version.txt
Labels: CLA Signed, ciflow/binaries/all

#652 Update versions and README after 0.3 release
  README.md
  version.txt
Labels: CLA Signed

#654 Remove future work section
  README.md
Labels: CLA Signed

#656 Add TORCHCODEC_DISABLE_COMPILE_WARNING_AS_ERROR environment variable to disable -Werror compilation option
  setup.py
  src/torchcodec/_core/CMakeLists.txt
Labels: CLA Signed

#658 cpp_tests: Switch to only use conda-forge and add back ffmpeg 6
  .github/workflows/cpp_tests.yaml
Labels: CLA Signed

#635 Support encoding into a bytes tensor
  src/torchcodec/_core/AVIOBytesContext.cpp
  src/torchcodec/_core/AVIOBytesContext.h
  src/torchcodec/_core/AVIOContextHolder.cpp
  src/torchcodec/_core/AVIOContextHolder.h
  src/torchcodec/_core/AVIOFileLikeContext.cpp
  src/torchcodec/_core/CMakeLists.txt
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
  src/torchcodec/_core/FFMPEGCommon.cpp
  src/torchcodec/_core/FFMPEGCommon.h
  src/torchcodec/_core/__init__.py
  src/torchcodec/_core/custom_ops.cpp
  src/torchcodec/_core/ops.py
  test/test_ops.py
Labels: CLA Signed

#664 Audio: Fix output shape when start==stop
  src/torchcodec/_core/SingleStreamDecoder.cpp
  test/test_decoders.py
  test/test_ops.py
Labels: bug, CLA Signed

#665 AudioDecoder: Fix output when stop < start of first frame
  src/torchcodec/_core/SingleStreamDecoder.cpp
  test/test_decoders.py
  test/test_ops.py
Labels: bug, CLA Signed
