Repository meta-pytorch/torchcodec, pull requests merged in 2025-08, with the labels that each got.

#808 Release 0.6
  .github/workflows/build_ffmpeg.yaml
  .github/workflows/docs.yaml
  .github/workflows/linux_cuda_wheel.yaml
  .github/workflows/linux_wheel.yaml
  .github/workflows/macos_wheel.yaml
  version.txt
Labels: CLA Signed, ciflow/binaries/all

#813 [EZ] Replace `pytorch-labs` with `pytorch`
  src/torchcodec/_core/SingleStreamDecoder.cpp
Labels: CLA Signed

#809 Update version and README version table
  README.md
  version.txt
Labels: CLA Signed

#754 Support encoding to file-like object
  src/torchcodec/_core/AVIOContextHolder.cpp
  src/torchcodec/_core/AVIOContextHolder.h
  src/torchcodec/_core/AVIOFileLikeContext.cpp
  src/torchcodec/_core/AVIOFileLikeContext.h
  src/torchcodec/_core/AVIOTensorContext.cpp
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_core/Encoder.h
  src/torchcodec/_core/__init__.py
  src/torchcodec/_core/ops.py
  src/torchcodec/_core/pybind_ops.cpp
  src/torchcodec/encoders/_audio_encoder.py
  test/test_encoders.py
Labels: CLA Signed

#812 Tests: fix tests if running with self-built ffmpeg
  src/torchcodec/_core/custom_ops.cpp
  test/test_metadata.py
  test/utils.py
Labels: CLA Signed

#817 test: rename cpu_and_cuda to all_supported_devices
  test/conftest.py
  test/test_decoders.py
  test/test_ops.py
  test/utils.py
Labels: CLA Signed

#830 Apply C++ lints
  src/torchcodec/_core/Cache.h
Labels: CLA Signed

#835 Call spec.loader.exec_module in _load_pybind11_module utility
  src/torchcodec/_internally_replaced_utils.py
Labels: CLA Signed

#838 Correct `seek` signature to return `int` instead of `bytes`
  examples/decoding/file_like.py
  src/torchcodec/decoders/_audio_decoder.py
  src/torchcodec/decoders/_decoder_utils.py
  src/torchcodec/decoders/_video_decoder.py
  test/test_decoders.py
  test/test_ops.py
Labels: CLA Signed

#842 [TorchCodec] Late-init TorchVision imports
  benchmarks/decoders/benchmark_decoders_library.py
Labels: CLA Signed, fb-exported

#852 Allow AudioEncoder.to_file to accept Path
  src/torchcodec/encoders/_audio_encoder.py
  test/test_encoders.py
Labels: CLA Signed

#851 Shorter frame-mapping test name
  test/test_decoders.py
Labels: CLA Signed

#806 Fix Windows build and add Windows CPU tests
  .github/workflows/windows_wheel.yaml
  setup.py
  src/torchcodec/_core/CMakeLists.txt
  src/torchcodec/_core/Encoder.cpp
  src/torchcodec/_internally_replaced_utils.py
  test/test_encoders.py
  test/utils.py
Labels: CLA Signed

#828 Update resource generation script to python
  .github/workflows/reference_resources.yaml
  test/convert_image_to_tensor.py
  test/generate_reference_resources.py
  test/generate_reference_resources.sh
  test/utils.py
Labels: CLA Signed

#854 Use main branch of test-infra for Windows builds
  .github/workflows/windows_wheel.yaml
Labels: CLA Signed

#856 Fix implicit conversion of int64 to int
  src/torchcodec/_core/CMakeLists.txt
  src/torchcodec/_core/ValidationUtils.cpp
  src/torchcodec/_core/ValidationUtils.h
  src/torchcodec/_core/custom_ops.cpp
  src/torchcodec/_core/pybind_ops.cpp
Labels: CLA Signed
